### ISSUE TITLE
Can't delete db folder

### ISSUE THREAD

**Issue by 21pl** [gmickel/memorybot#5]
Great work! But I have an issue where when I try to start afresh by removing the db folder I get the below error. Same error occurs when I try to point to a new folder in the .env file. The only way I've been able to start again is to delete and re-install the whole repository 

(memorybot) lp9@lp-mbp-8401 memorybot % npm start

> memory-chatterbox@0.0.1 start
> npm run build && node -r dotenv/config dist/index.js

> memory-chatterbox@0.0.1 build
> tsc --declaration --outDir dist/

⠋ Creating new Context Vector Store in the /Users/lp9/memorybot/db directoryfile:///Users/lp9/memorybot/dist/lib/contextManager.js:66
            throw new Error(`Unsupported file extension: ${fileExtension}`);
                  ^

Error: Unsupported file extension: 
    at loadAndSplitFile (file:///Users/lp9/memorybot/dist/lib/contextManager.js:66:19)
    at file:///Users/lp9memorybot/dist/lib/contextManager.js:89:74
    at Array.map (<anonymous>)
    at loadOrCreateVectorStore (file:///Users/lp9/memorybot/dist/lib/contextManager.js:89:56)
    at async file:///Users/lp9/memorybot/dist/lib/contextManager.js:97:28

Node.js v18.15.0

on a mac M1

**Comment by 21pl** [comment]
just tried reinstalling everything with the updates and now get the following error when i try to 'npm start' or 'npm run dev'

(memorybot) lp9@lp-mbp-8401 memorybot % npm start

> memory-chatterbox@0.0.1 start
> npm run build && node -r dotenv/config dist/index.js


> memory-chatterbox@0.0.1 build
> tsc --declaration --outDir dist/

node:internal/errors:490
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'commands' imported from /Users/lp9/memorybot/dist/commands.js
    at new NodeError (node:internal/errors:399:5)
    at packageResolve (node:internal/modules/esm/resolve:889:9)
    at moduleResolve (node:internal/modules/esm/resolve:938:20)
    at defaultResolve (node:internal/modules/esm/resolve:1153:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:838:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
    at link (node:internal/modules/esm/module_job:76:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v18.15.0

**Comment by gmickel** [comment]
Sorry about that, it would seem my VSCode is auto-importing invalid paths. Fix being pushed as I type this.
